In [1]:
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv('../data/phones.csv')

In [5]:
dataset.head()

,Unnamed: 0,Unnamed: 0.1,URL,Price,Marka,Model,İşletim Sistemi,Ön Kamera Çözünürlüğü,Arka Kamera Çözünürlüğü,Bellek Kapasitesi,...,5G Desteği,Yüz Tanıma,Toza Dayanıklılık Seviyesi,Suya Dayanıklılık Seviyesi,1.Yardımcı İşlemci,İkinci Ön Kamera Çözünürlüğü,Kamera Zoom,2.Yardımcı İşlemci,Beşinci Arka Kamera Çözünürlüğü,Dahili_Hafiza
0,0,0,https://www.n11.com/urun/samsung-galaxy-m51-du...,"4.999,00",Samsung,M51,Android,32 MP,64 MP,8 GB,...,Yok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128.0
1,1,1,https://www.n11.com/urun/samsung-galaxy-m31-12...,"3.239,00",Samsung,Galaxy M31,Android,32 MP,64 MP,6 GB,...,Yok,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128.0
2,2,2,https://www.n11.com/urun/samsung-galaxy-m21-du...,"2.609,90",Samsung,Galaxy M21 Duos,Android,20 MP,48 MP,4 GB,...,NaN,Var,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.0
3,3,3,https://www.n11.com/urun/xiaomi-poco-x3-nfc-12...,"3.790,00",Xiaomi,X3 NFC,Android,20 MP,64 MP,6 GB,...,NaN,Var,IP5X,IPX3,Hexa-core 1.8 GHz ARM Cortex-A55,NaN,NaN,NaN,NaN,128.0
4,4,4,https://www.n11.com/urun/xiaomi-redmi-note-9-p...,"3.715,00",Xiaomi,Redmi Note 9 Pro,Android,16 MP,64 MP,6 GB,...,Yok,Var,NaN,NaN,NaN,NaN,NaN,NaN,NaN,128.0

In [33]:
dataset["Marka"] = dataset.Marka.str.replace(' ', '')
list_marka = dataset["Marka"].unique()

In [35]:
list_marka.sort()

In [36]:
list_marka = list(list_marka)

In [37]:
marka_index=list_marka.index("Samsung")
marka_index

17

In [38]:
marka_index=list_marka.index("Xiaomi")
marka_index

21

In [41]:
df_markalar = pd.DataFrame()

In [42]:
df_markalar["Markalar"] = list_marka

In [43]:
df_markalar

         Markalar
0         Alcatel
1           Apple
2        C5Mobile
3          Casper
4        Elephone
5   GeneralMobile
6          Hiking
7           Honor
8          Huawei
9         Infinix
10             LG
11         Lenovo
12          Meizu
13           Oppo
14     OppoRealme
15           Poco
16         Reeder
17        Samsung
18            Tcl
19       Turkcell
20         Vestel
21         Xiaomi

In [45]:
df_markalar.to_csv("../data/markalar.csv",index=False)